(()=>{'use strict';
const menu=document.querySelector('.menu-toggle'), mobileMenu=document.querySelector('#mobile-menu');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));menu.setAttribute('aria-label',open?'Open menu':'Close menu');mobileMenu.hidden=open});
mobileMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.hidden=true;menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open menu')}));
let lastTrigger=null;const dialogs=document.querySelectorAll('#booking-dialog');
function openDialog(dialog,trigger){lastTrigger=trigger;dialog.showModal();document.body.classList.add('modal-open')}
dialogs.forEach(d=>{d.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>d.close()));d.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastTrigger?.focus()});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
const booking=document.querySelector('#booking-dialog'),bookingFrame=document.querySelector('#booking-widget'),widgetStatus=document.querySelector('#widget-status');let bookingLoaded=false,bookingReady=false,bookingTimer;
document.querySelectorAll('[data-book]').forEach(b=>b.addEventListener('click',()=>{openDialog(booking,b);if(window.gtag)gtag('event','booking_window_open',{event_category:'booking',button_text:b.textContent.trim()});if(bookingLoaded)return;bookingLoaded=true;bookingFrame.src=bookingFrame.dataset.src;bookingTimer=setTimeout(()=>{if(!bookingReady){bookingFrame.parentElement.hidden=true;widgetStatus.textContent='Date search is taking longer than expected. Open direct booking below to choose dates and see the current total.'}},12000)}));
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==bookingFrame.contentWindow)return;if(e.data?.type==='manor-booking-ready'){bookingReady=true;clearTimeout(bookingTimer);bookingFrame.parentElement.hidden=false;widgetStatus.textContent='Choose your dates, or open direct booking below. The booking provider confirms current availability.'}if(e.data?.type==='manor-booking-unavailable'){widgetStatus.textContent='Live availability could not be verified here. Open direct booking below for confirmed dates and the full stay total.'}if(e.data?.type==='manor-booking-height')bookingFrame.style.height=Math.min(700,Math.max(150,Number(e.data.height)||180))+'px';if(e.data?.type==='manor-booking-close')booking.close()});
const scenes={hotTub:{image:'hotTub-concept',alt:'Digitally edited image: the existing hot tub opened, with blue underwater lighting and jets running',copy:'Blue water. Warm lights.<br>Absolutely nowhere to be.',disclosure:'Edited from the actual property photo. Open water and jets are generated; the owner confirms blue lighting.'},firepit:{image:'firepit-concept-v2',alt:'Digitally edited image: a contained fire in the real backyard, with background utility pole and power lines digitally removed',copy:'One more story.<br>One more minute by the fire.',disclosure:'Digitally edited: fire and warm glow added; background utility pole and power lines digitally removed.'}};
document.querySelectorAll('[data-evening]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-evening]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});const s=scenes[b.dataset.evening],img=document.querySelector('#evening-image');img.src=`Images/redesign/${s.image}-1600.webp`;img.alt=s.alt;document.querySelector('#evening-copy').innerHTML=s.copy;document.querySelector('#evening-disclosure').textContent=s.disclosure}));
// The same-origin review dashboard navigates matching sections without modifying content.
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.type!=='manor-review-section')return;document.getElementById(e.data.id)?.scrollIntoView({behavior:'instant',block:'start'})});
if(new URLSearchParams(location.search).get("book")==="1"){const trigger=[...document.querySelectorAll("[data-book]")].find(e=>e.offsetParent);trigger?.click()}
})();
