(()=>{'use strict';
const menu=document.querySelector('.menu-toggle'), mobileMenu=document.querySelector('#mobile-menu');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));menu.setAttribute('aria-label',open?'Open menu':'Close menu');mobileMenu.hidden=open});
mobileMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.hidden=true;menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open menu')}));
let lastTrigger=null;const dialogs=document.querySelectorAll('dialog');
function openDialog(dialog,trigger){lastTrigger=trigger;dialog.showModal();document.body.classList.add('modal-open')}
dialogs.forEach(d=>{d.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>d.close()));d.addEventListener('close',()=>{document.body.classList.remove('modal-open');lastTrigger?.focus()});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
const booking=document.querySelector('#booking-dialog'),bookingFrame=document.querySelector('#booking-widget'),widgetStatus=document.querySelector('#widget-status');let bookingLoaded=false,bookingReady=false,bookingTimer;
document.querySelectorAll('[data-book]').forEach(b=>b.addEventListener('click',()=>{openDialog(booking,b);if(window.gtag)gtag('event','booking_window_open',{event_category:'booking',button_text:b.textContent.trim()});if(bookingLoaded)return;bookingLoaded=true;bookingFrame.src=bookingFrame.dataset.src;bookingTimer=setTimeout(()=>{if(!bookingReady){bookingFrame.parentElement.hidden=true;widgetStatus.textContent='Date search is taking longer than expected. Open direct booking below to choose dates and see the current total.'}},12000)}));
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==bookingFrame.contentWindow)return;if(e.data?.type==='manor-booking-ready'){bookingReady=true;clearTimeout(bookingTimer);bookingFrame.parentElement.hidden=false;widgetStatus.textContent='Choose your dates, or open direct booking below. The booking provider confirms current availability.'}if(e.data?.type==='manor-booking-unavailable'){widgetStatus.textContent='Live availability could not be verified here. Open direct booking below for confirmed dates and the full stay total.'}if(e.data?.type==='manor-booking-height')bookingFrame.style.height=Math.min(700,Math.max(150,Number(e.data.height)||180))+'px';if(e.data?.type==='manor-booking-close')booking.close()});
const scenes={hotTub:{image:'hotTub-concept',alt:'Digitally edited image: the existing hot tub opened, with blue underwater lighting and jets running',copy:'Blue water. Warm lights.<br>Absolutely nowhere to be.',disclosure:'Edited from the actual property photo. Open water and jets are generated; the owner confirms blue lighting.'},firepit:{image:'firepit-concept-v2',alt:'Digitally edited image: a contained fire in the real backyard, with background utility pole and power lines digitally removed',copy:'One more story.<br>One more minute by the fire.',disclosure:'Digitally edited: fire and warm glow added; background utility pole and power lines digitally removed.'}};
document.querySelectorAll('[data-evening]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-evening]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});const s=scenes[b.dataset.evening],img=document.querySelector('#evening-image');img.src=`Images/redesign/${s.image}-1600.webp`;img.alt=s.alt;document.querySelector('#evening-copy').innerHTML=s.copy;document.querySelector('#evening-disclosure').textContent=s.disclosure}));
const all=JSON.parse(document.querySelector('#gallery-data').textContent);let filtered=all,index=0;const gallery=document.querySelector('#gallery-dialog'),thumbs=document.querySelector('.gallery-thumbs');
function renderPhoto(){const item=filtered[index];if(!item)return;const img=document.querySelector('#gallery-photo');img.src=`Images/redesign/${item.name}-1600.webp`;img.alt=item.caption;document.querySelector('#gallery-caption').textContent=item.caption;document.querySelector('#gallery-count').textContent=`${index+1} / ${filtered.length}`;thumbs.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-current',String(i===index)));thumbs.querySelector(`[data-index="${index}"]`)?.scrollIntoView({block:'nearest',inline:'nearest'})}
function makeThumbs(){thumbs.replaceChildren();filtered.forEach((item,i)=>{const b=document.createElement('button');b.type='button';b.dataset.index=i;b.setAttribute('aria-label',`View ${item.caption}`);const img=document.createElement('img');img.src=`Images/redesign/${item.name}-640.webp`;img.alt='';img.loading='lazy';b.append(img);b.addEventListener('click',()=>{index=i;renderPhoto()});thumbs.append(b)})}
function filter(category){filtered=category==='All'?all:all.filter(x=>x.category===category);index=0;document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===category)));makeThumbs();renderPhoto()}
document.querySelectorAll('[data-gallery-open]').forEach(b=>b.addEventListener('click',()=>{filter('All');index=Number(b.dataset.galleryOpen);openDialog(gallery,b);renderPhoto()}));document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>filter(b.dataset.category)));
function move(delta){index=(index+delta+filtered.length)%filtered.length;renderPhoto()}
document.querySelector('.gallery-prev').addEventListener('click',()=>move(-1));document.querySelector('.gallery-next').addEventListener('click',()=>move(1));gallery.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}if(e.key==='ArrowRight'){e.preventDefault();move(1)}});
// The same-origin review dashboard navigates matching sections without modifying content.
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.type!=='manor-review-section')return;document.getElementById(e.data.id)?.scrollIntoView({behavior:'instant',block:'start'})});
if(new URLSearchParams(location.search).get("book")==="1"){const trigger=[...document.querySelectorAll("[data-book]")].find(e=>e.offsetParent);trigger?.click()}
})();
