/* Run after editing content/journal.json. No package installation required. */
const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');
const site='https://mojomanorwaynesville.com';const data=JSON.parse(fs.readFileSync(path.join(root,'content/journal.json'),'utf8'));const articles=data.articles;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const seen=new Set();for(const a of articles){if(seen.has(a.slug))throw Error('Duplicate journal slug: '+a.slug);seen.add(a.slug);if(!/^[a-z0-9-]+$/.test(a.slug))throw Error('Invalid slug');if(!fs.existsSync(path.join(root,'blog',a.slug+'.html')))throw Error('Article file missing: '+a.slug);if(!a.published||Number.isNaN(Date.parse(a.published)))throw Error('Publication date missing: '+a.slug);if(!fs.existsSync(path.join(root,a.image.replace(/^\//,''))))throw Error('Image missing: '+a.image)}
const cards=articles.map(a=>`<a href="${esc(a.url)}" class="blog-card" data-topic="${esc(a.topic)}"><div class="blog-card-img"><img src="${esc(a.image)}" alt="${esc(a.imageAlt)}" loading="lazy" width="1200" height="800"></div><div class="blog-card-content"><p class="blog-card-tag">${esc(a.tag)}</p><h2 class="blog-card-title">${esc(a.title)}</h2><p class="blog-card-excerpt">${esc(a.excerpt)}</p><p class="blog-card-meta">${esc(a.displayDate)}</p></div></a>`).join('\n');
let index=fs.readFileSync(path.join(root,'blog/index.html'),'utf8');index=index.replace(/<!-- JOURNAL_CARDS_START -->[\s\S]*?<!-- JOURNAL_CARDS_END -->/,'<!-- JOURNAL_CARDS_START -->\n'+cards+'\n<!-- JOURNAL_CARDS_END -->');index=index.replace(/(<p id="journal-status"[^>]*>)[\s\S]*?<\/p>/,`$1${articles.length} guides to explore</p>`);index=index.replace(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g,(all,json)=>{let obj;try{obj=JSON.parse(json)}catch{return all}if(obj['@type']!=='Blog')return all;obj.blogPost=articles.map(a=>({'@type':'BlogPosting',headline:a.title,url:site+a.url,datePublished:a.published,description:a.excerpt,image:site+a.image}));return '<script type="application/ld+json">'+JSON.stringify(obj)+'</script>'});fs.writeFileSync(path.join(root,'blog/index.html'),index);
const latest=[...articles].sort((a,b)=>b.published.localeCompare(a.published));const rss=`<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>${esc(data.name)} — Mojo Manor</title><link>${site}/blog/</link><description>${esc(data.description)}</description><language>en-us</language><atom:link href="${site}/feed.xml" rel="self" type="application/rss+xml"/>${latest.map(a=>`<item><title>${esc(a.title)}</title><link>${site}${esc(a.url)}</link><guid isPermaLink="true">${site}${esc(a.url)}</guid><pubDate>${new Date(a.published+'T12:00:00Z').toUTCString()}</pubDate><description>${esc(a.excerpt)}</description></item>`).join('\n')}</channel></rss>\n`;fs.writeFileSync(path.join(root,'feed.xml'),rss);
for(const a of articles){
 const file=path.join(root,'blog',a.slug+'.html');let html=fs.readFileSync(file,'utf8');
 html=html.replace(/(<div class="blog-post-hero[^>]*>[\s\S]*?)<img\b[^>]*>/,(_,prefix)=>prefix+`<img src="${esc(a.image)}" alt="${esc(a.imageAlt)}" loading="eager" fetchpriority="high" width="1200" height="800">`);
 html=html.replace(/<meta\s+(?:property|name)="(og:image|twitter:image)"[^>]*>/g,(_,kind)=>`<meta ${kind.startsWith('og:')?'property':'name'}="${kind}" content="${site+esc(a.image)}">`);
 html=html.replace(/<a\b[^>]*class="[^"]*blog-card[^\"]*"[^>]*>[\s\S]*?<\/a>/g,card=>{
  const href=card.match(/href="([^"]+)"/)?.[1];if(!href)return card;
  const slug=new URL(href,site+a.url).pathname.split('/').pop().replace(/\.html$/,'');const related=articles.find(r=>r.slug===slug);if(!related)return card;
  return card.replace(/<source\b[^>]*>/g,'').replace(/<img\b[^>]*>/,`<img src="${esc(related.image)}" alt="${esc(related.imageAlt)}" loading="lazy" width="1200" height="800">`);
 });
 html=html.replace(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g,(all,json)=>{let o;try{o=JSON.parse(json)}catch{return all}if(!['Article','BlogPosting'].includes(o['@type']))return all;o.image=site+a.image;return '<script type="application/ld+json">'+JSON.stringify(o)+'</script>'});fs.writeFileSync(file,html.replace(/[\t ]+$/gm,''))
}
const homepagePath=path.join(root,'index.html');let homepage=fs.readFileSync(homepagePath,'utf8');
if(homepage.includes('<!-- HOMEPAGE_BLOG_START -->')){
 const featured=articles.filter(a=>a.homepageFeatured).slice(0,3);
 if(!featured.length)throw Error('Choose at least one homepageFeatured article in content/journal.json');
 const previews=featured.map(a=>`<a class="homepage-blog-card" href="${esc(a.url)}"><div class="homepage-blog-photo"><img src="${esc(a.image)}" alt="${esc(a.imageAlt)}" width="1200" height="800" loading="lazy" decoding="async"></div><p class="eyebrow">${esc(a.tag)}</p><h3>${esc(a.title)}</h3><p>${esc(a.homepageSummary||a.excerpt)}</p><span class="text-link">Read the guide <span aria-hidden="true">↗</span></span></a>`).join('\n');
 homepage=homepage.replace(/<!-- HOMEPAGE_BLOG_START -->[\s\S]*?<!-- HOMEPAGE_BLOG_END -->/,'<!-- HOMEPAGE_BLOG_START -->\n'+previews+'\n<!-- HOMEPAGE_BLOG_END -->');fs.writeFileSync(homepagePath,homepage);
}
console.log(`Built ${articles.length} journal cards, matching Blog schema, feed.xml and homepage article previews.`);
