/* Run after editing content/journal.json. No package installation required. */
const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');
const site='https://mojomanorwaynesville.com';const data=JSON.parse(fs.readFileSync(path.join(root,'content/journal.json'),'utf8'));const articles=data.articles;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const imageStyle=a=>a.imagePosition?' style="object-position:'+esc(a.imagePosition)+';"':'';
const imageCreditHtml=c=>`<a href="${esc(c.source)}">${esc(c.title)}</a> by ${esc(c.author)} · <a href="${esc(c.licenseUrl)}">${esc(c.license)}</a>. ${esc(c.changes)}`;
const seen=new Set();for(const a of articles){if(seen.has(a.slug))throw Error('Duplicate journal slug: '+a.slug);seen.add(a.slug);if(!/^[a-z0-9-]+$/.test(a.slug))throw Error('Invalid slug');if(!fs.existsSync(path.join(root,'blog',a.slug+'.html')))throw Error('Article file missing: '+a.slug);if(!a.published||Number.isNaN(Date.parse(a.published)))throw Error('Publication date missing: '+a.slug);if(!fs.existsSync(path.join(root,a.image.replace(/^\//,''))))throw Error('Image missing: '+a.image)}
const cards=articles.map(a=>`<a href="${esc(a.url)}" class="blog-card" data-topic="${esc(a.topic)}"><div class="blog-card-img"><img src="${esc(a.image)}" alt="${esc(a.imageAlt)}"${imageStyle(a)} loading="lazy" width="1200" height="800"></div><div class="blog-card-content"><p class="blog-card-tag">${esc(a.tag)}</p><h2 class="blog-card-title">${esc(a.title)}</h2><p class="blog-card-excerpt">${esc(a.excerpt)}</p><p class="blog-card-meta">${esc(a.displayDate)}</p></div></a>`).join('\n');
let index=fs.readFileSync(path.join(root,'blog/index.html'),'utf8');index=index.replace(/<!-- JOURNAL_CARDS_START -->[\s\S]*?<!-- JOURNAL_CARDS_END -->/,'<!-- JOURNAL_CARDS_START -->\n'+cards+'\n<!-- JOURNAL_CARDS_END -->');index=index.replace(/(<p id="journal-status"[^>]*>)[\s\S]*?<\/p>/,`$1${articles.length} guides to explore</p>`);index=index.replace(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g,(all,json)=>{let obj;try{obj=JSON.parse(json)}catch{return all}if(obj['@type']!=='Blog')return all;obj.blogPost=articles.map(a=>({'@type':'BlogPosting',headline:a.title,url:site+a.url,datePublished:a.published,description:a.excerpt,image:site+a.image}));return '<script type="application/ld+json">'+JSON.stringify(obj)+'</script>'});index=index.replace(/<!-- JOURNAL_IMAGE_CREDITS_START -->[\s\S]*?<!-- JOURNAL_IMAGE_CREDITS_END -->/,'');const credits=[...new Map(articles.filter(a=>a.imageCredit).map(a=>[a.imageCredit.source,a.imageCredit])).values()];if(credits.length)index=index.replace('<!-- JOURNAL_CARDS_END --></div>','<!-- JOURNAL_CARDS_END --></div><!-- JOURNAL_IMAGE_CREDITS_START --><p style="font-size:12px;line-height:1.7;color:#657060;">Image credit: '+credits.map(imageCreditHtml).join(' ')+'</p><!-- JOURNAL_IMAGE_CREDITS_END -->');fs.writeFileSync(path.join(root,'blog/index.html'),index);
const latest=[...articles].sort((a,b)=>b.published.localeCompare(a.published));const rss=`<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>${esc(data.name)} — Mojo Manor</title><link>${site}/blog/</link><description>${esc(data.description)}</description><language>en-us</language><atom:link href="${site}/feed.xml" rel="self" type="application/rss+xml"/>${latest.map(a=>`<item><title>${esc(a.title)}</title><link>${site}${esc(a.url)}</link><guid isPermaLink="true">${site}${esc(a.url)}</guid><pubDate>${new Date(a.published+'T12:00:00Z').toUTCString()}</pubDate><description>${esc(a.excerpt)}</description></item>`).join('\n')}</channel></rss>\n`;fs.writeFileSync(path.join(root,'feed.xml'),rss);
for(const a of articles){
 const file=path.join(root,'blog',a.slug+'.html');let html=fs.readFileSync(file,'utf8');
 html=html.replace(/\s*<p class="hero-photo-credit"[^>]*>[\s\S]*?<\/p>/g,'');
 html=html.replace(/(<div class="blog-post-hero[^>]*>[\s\S]*?)<img\b[^>]*>/,(_,prefix)=>prefix+`<img src="${esc(a.image)}" alt="${esc(a.imageAlt)}"${imageStyle(a)} loading="eager" fetchpriority="high" width="1200" height="800">`);
 if(a.imageCredit)html=html.replace(/(<div class="blog-post-hero[^>]*>[\s\S]*?<\/div>)/,`$1\n<p class="hero-photo-credit" style="font-size:12px;line-height:1.7;color:#e1e8de;margin:-1.5rem 0 0;padding-bottom:1.5rem;">Photo: ${imageCreditHtml(a.imageCredit)}</p>`);
 html=html.replace(/<meta\s+(?:property|name)="(og:image|twitter:image)"[^>]*>/g,(_,kind)=>`<meta ${kind.startsWith('og:')?'property':'name'}="${kind}" content="${site+esc(a.image)}">`);
 html=html.replace(/<a\b[^>]*class="[^"]*blog-card[^\"]*"[^>]*>[\s\S]*?<\/a>/g,card=>{
  const href=card.match(/href="([^"]+)"/)?.[1];if(!href)return card;
  const slug=new URL(href,site+a.url).pathname.split('/').pop().replace(/\.html$/,'');const related=articles.find(r=>r.slug===slug);if(!related)return card;
  return card.replace(/<source\b[^>]*>/g,'').replace(/<img\b[^>]*>/,`<img src="${esc(related.image)}" alt="${esc(related.imageAlt)}"${imageStyle(related)} loading="lazy" width="1200" height="800">`);
 });
 // Related cards follow the index title when an existing guide is refreshed.
 const relatedStart=html.indexOf('<!-- RELATED POSTS -->');
 if(relatedStart!==-1){let relatedHtml=html.slice(relatedStart);relatedHtml=relatedHtml.replace(/<a\b[^>]*href="([^"]+)"[^>]*>[\s\S]*?<\/a>/g,(card,href)=>{const slug=new URL(href,site+a.url).pathname.split('/').pop().replace(/\.html$/,'');const related=articles.find(r=>r.slug===slug);if(!related)return card;if(/class="blog-card-title"/.test(card))return card.replace(/(<(?:h2|h3|p)\b[^>]*class="blog-card-title"[^>]*>)[\s\S]*?(<\/(?:h2|h3|p)>)/,`$1${esc(related.title)}$2`).replace(/(<p\b[^>]*class="blog-card-meta"[^>]*>)[\s\S]*?(<\/p>)/,`$1${esc(related.displayDate)}$2`);return card.replace(/(<p\b[^>]*>)[^<]*→\s*(<\/p>)/,`$1${esc(related.title)} →$2`)});html=html.slice(0,relatedStart)+relatedHtml;}
 html=html.replace(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g,(all,json)=>{let o;try{o=JSON.parse(json)}catch{return all}if(!['Article','BlogPosting'].includes(o['@type']))return all;o.image=site+a.image;o.datePublished=a.published;if(a.modified){if(Number.isNaN(Date.parse(a.modified))||a.modified<a.published)throw Error('Invalid modified date: '+a.slug);o.dateModified=a.modified}o.mainEntityOfPage=site+a.url;return '<script type="application/ld+json">'+JSON.stringify(o)+'</script>'});fs.writeFileSync(file,html.replace(/[\t ]+$/gm,''))
}
const homepagePath=path.join(root,'index.html');let homepage=fs.readFileSync(homepagePath,'utf8');
if(homepage.includes('<!-- HOMEPAGE_BLOG_START -->')){
 const featured=articles.filter(a=>a.homepageFeatured).slice(0,3);
 if(!featured.length)throw Error('Choose at least one homepageFeatured article in content/journal.json');
 const previews=featured.map(a=>`<a class="homepage-blog-card" href="${esc(a.url)}"><div class="homepage-blog-photo"><img src="${esc(a.image)}" alt="${esc(a.imageAlt)}" width="1200" height="800" loading="lazy" decoding="async"></div><p class="eyebrow">${esc(a.tag)}</p><h3>${esc(a.homepageTitle||a.title)}</h3><p>${esc(a.homepageSummary||a.excerpt)}</p><span class="text-link">Read the guide <span aria-hidden="true">↗</span></span></a>`).join('\n');
 homepage=homepage.replace(/<!-- HOMEPAGE_BLOG_START -->[\s\S]*?<!-- HOMEPAGE_BLOG_END -->/,'<!-- HOMEPAGE_BLOG_START -->\n'+previews+'\n<!-- HOMEPAGE_BLOG_END -->');fs.writeFileSync(homepagePath,homepage);
}
const sitemapPath=path.join(root,'sitemap.xml');let sitemap=fs.readFileSync(sitemapPath,'utf8');
for(const a of articles){const pattern=new RegExp('(<loc>'+site+a.url+'</loc>\\s*<lastmod>)[^<]*(</lastmod>)');const publishedHtml=fs.readFileSync(path.join(root,'blog',a.slug+'.html'),'utf8');const existingModified=publishedHtml.match(/"dateModified":"([0-9-]+)"/)?.[1];const lastmod=a.modified||[a.published,existingModified].filter(Boolean).sort().pop();if(!pattern.test(sitemap))sitemap=sitemap.replace('</urlset>',`  <url><loc>${site+a.url}</loc><lastmod>${lastmod}</lastmod></url>\n</urlset>`);else sitemap=sitemap.replace(pattern,`$1${lastmod}$2`)}
if(!sitemap.includes('<loc>'+site+'/tour</loc>'))sitemap=sitemap.replace('</urlset>',`  <url><loc>${site}/tour</loc><lastmod>2026-09-06</lastmod></url>\n</urlset>`);
fs.writeFileSync(sitemapPath,sitemap);
console.log(`Built ${articles.length} journal cards, Blog schema, feed.xml, sitemap dates and homepage article previews.`);
